# Generated by Django 3.0.5 on 2020-05-14 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('SurveyID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('JobNumber', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Project', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('Survey', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vehicular', 'Vehicular Count'), ('Pedestrian', 'Pedestrian Count'), ('Public Transport', 'Public Transport Count'), ('Parking', 'Parking Survey'), ('Illegal Parking', 'Illegal Parking Survey'), ('Queue Length', 'Queue Length'), ('Interview', 'Interview')], default=None, max_length=84, null=True)),
                ('Author', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('IssueDate', models.DateField(blank=True, default=None, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('PaymentStatus', models.DateField(blank=True, default=None, null=True)),
                ('Remark', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TStart', models.TimeField()),
                ('TEnd', models.TimeField()),
                ('TTag', models.CharField(choices=[('1', 'am'), ('2', 'pm'), ('3', 'noon'), ('4', 'night'), ('5', '24hr'), ('6', 'others')], max_length=10)),
                ('SurveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='bokehMap.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('locations', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('Survey', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vehicular', 'Vehicular Count'), ('Pedestrian', 'Pedestrian Count'), ('Public Transport', 'Public Transport Count'), ('Parking', 'Parking Survey'), ('Illegal Parking', 'Illegal Parking Survey'), ('Queue Length', 'Queue Length'), ('Interview', 'Interview')], default='', max_length=84, null=True)),
                ('SurveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokehMap.Survey')),
            ],
        ),
    ]
